package mdm

import (
	"fmt"
	"io"
	"text/template"

	"github.com/meetflowstate/flowstate-telemetry/internal/config"
)

const ansibleTemplate = `---
# Flowstate Telemetry — Ansible Playbook
# Generated by flowstate-telemetry generate-mdm --format ansible
# Usage: ansible-playbook flowstate-telemetry.yml -i inventory

- name: Configure Flowstate AI Telemetry
  hosts: developers
  become: false
  vars:
    flowstate_endpoint: "{{ "{{ flowstate_endpoint | default('" }}{{ .Endpoint }}{{ "') }}" }}"
    flowstate_key: "{{ "{{ flowstate_key | default('" }}{{ .Key }}{{ "') }}" }}"

  tasks:
    - name: Set system environment variables
      become: true
      lineinfile:
        path: /etc/environment
        regexp: "^{{ "{{ item.key }}" }}="
        line: "{{ "{{ item.key }}={{ item.value }}" }}"
        create: true
      loop:
        - { key: "FLOWSTATE_OTLP_ENDPOINT", value: "{{ "{{ flowstate_endpoint }}" }}" }
        - { key: "FLOWSTATE_OTLP_KEY", value: "{{ "{{ flowstate_key }}" }}" }
        - { key: "OTEL_RESOURCE_ATTRIBUTES", value: "service.name=flowstate-telemetry" }

    - name: Ensure Claude Code config directory exists
      file:
        path: "{{ "{{ ansible_env.HOME }}" }}/.claude"
        state: directory
        mode: "0755"

    - name: Configure Claude Code telemetry
      copy:
        dest: "{{ "{{ ansible_env.HOME }}" }}/.claude/settings.json"
        content: |
          {
            "env": {
              "CLAUDE_CODE_ENABLE_TELEMETRY": "1",
              "OTEL_METRICS_EXPORTER": "otlp",
              "OTEL_LOGS_EXPORTER": "otlp",
              "OTEL_EXPORTER_OTLP_PROTOCOL": "http/protobuf",
              "OTEL_EXPORTER_OTLP_ENDPOINT": "{{ "{{ flowstate_endpoint }}" }}",
              "OTEL_EXPORTER_OTLP_HEADERS": "x-flowstate-key={{ "{{ flowstate_key }}" }}",
              "OTEL_METRICS_TEMPORALITY_PREFERENCE": "cumulative",
              "OTEL_METRICS_INCLUDE_SESSION_ID": "true",
              "OTEL_METRICS_INCLUDE_ACCOUNT_UUID": "true"
            }
          }
        mode: "0644"
        force: false
      when: ansible_env.HOME is defined

    - name: Check if VS Code settings directory exists
      stat:
        path: "{{ "{{ ansible_env.HOME }}" }}/.config/Code/User"
      register: vscode_dir

    - name: Ensure VS Code settings directory exists
      file:
        path: "{{ "{{ ansible_env.HOME }}" }}/.config/Code/User"
        state: directory
        mode: "0755"
      when: vscode_dir.stat.exists

    - name: Configure VS Code Copilot Chat telemetry
      copy:
        dest: "{{ "{{ ansible_env.HOME }}" }}/.config/Code/User/settings.json"
        content: |
          {
            "github.copilot.chat.otel.enabled": true,
            "github.copilot.chat.otel.exporterType": "otlp-grpc",
            "github.copilot.chat.otel.otlpEndpoint": "{{ "{{ flowstate_endpoint }}" }}"
          }
        mode: "0644"
        force: false
      when: vscode_dir.stat.exists

    - name: Ensure Gemini config directory exists
      file:
        path: "{{ "{{ ansible_env.HOME }}" }}/.gemini"
        state: directory
        mode: "0755"
      when: lookup('pipe', 'which gemini', errors='ignore') != ''

    - name: Configure Gemini CLI telemetry
      copy:
        dest: "{{ "{{ ansible_env.HOME }}" }}/.gemini/settings.json"
        content: |
          {
            "telemetry": {
              "enabled": true,
              "target": "local",
              "otlpEndpoint": "{{ "{{ flowstate_endpoint }}" }}",
              "otlpProtocol": "grpc",
              "logPrompts": false
            }
          }
        mode: "0644"
        force: false
      when: lookup('pipe', 'which gemini', errors='ignore') != ''

    - name: Add shell profile environment variables
      blockinfile:
        path: "{{ "{{ ansible_env.HOME }}" }}/.bashrc"
        marker: "# {mark} Flowstate Telemetry"
        block: |
          export FLOWSTATE_OTLP_ENDPOINT="{{ "{{ flowstate_endpoint }}" }}"
          export FLOWSTATE_OTLP_KEY="{{ "{{ flowstate_key }}" }}"
          export OTEL_RESOURCE_ATTRIBUTES="service.name=flowstate-telemetry"
        create: true
`

// GenerateAnsible writes an Ansible playbook for Flowstate telemetry deployment.
func GenerateAnsible(w io.Writer, cfg config.Config) error {
	tmpl, err := template.New("ansible").Parse(ansibleTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	return tmpl.Execute(w, map[string]string{
		"Endpoint": cfg.Endpoint,
		"Key":      cfg.Key,
	})
}
