package mdm

import (
	"fmt"
	"io"
	"text/template"

	"github.com/meetflowstate/flowstate-telemetry/internal/config"
)

const intuneTemplate = `# Flowstate Telemetry — Microsoft Intune deployment script
# Generated by flowstate-telemetry generate-mdm --format intune
# Deploy via Intune > Devices > Scripts > Add (PowerShell)

$ErrorActionPreference = "Stop"

$Endpoint = "{{ .Endpoint }}"
$Key = "{{ .Key }}"

Write-Host "Configuring Flowstate Telemetry..."

# Set system-wide environment variables
[System.Environment]::SetEnvironmentVariable("FLOWSTATE_OTLP_ENDPOINT", $Endpoint, "Machine")
[System.Environment]::SetEnvironmentVariable("FLOWSTATE_OTLP_KEY", $Key, "Machine")
[System.Environment]::SetEnvironmentVariable("OTEL_RESOURCE_ATTRIBUTES", "service.name=flowstate-telemetry", "Machine")

# Also set for current user session
$env:FLOWSTATE_OTLP_ENDPOINT = $Endpoint
$env:FLOWSTATE_OTLP_KEY = $Key

# Configure Claude Code
$ClaudeDir = Join-Path $env:USERPROFILE ".claude"
$ClaudeSettings = Join-Path $ClaudeDir "settings.json"

if (-not (Test-Path $ClaudeDir)) {
    New-Item -ItemType Directory -Path $ClaudeDir -Force | Out-Null
}

$envBlock = @{
    "CLAUDE_CODE_ENABLE_TELEMETRY" = "1"
    "OTEL_METRICS_EXPORTER" = "otlp"
    "OTEL_LOGS_EXPORTER" = "otlp"
    "OTEL_EXPORTER_OTLP_PROTOCOL" = "http/protobuf"
    "OTEL_EXPORTER_OTLP_ENDPOINT" = $Endpoint
    "OTEL_EXPORTER_OTLP_HEADERS" = "x-flowstate-key=$Key"
    "OTEL_METRICS_TEMPORALITY_PREFERENCE" = "cumulative"
    "OTEL_METRICS_INCLUDE_SESSION_ID" = "true"
    "OTEL_METRICS_INCLUDE_ACCOUNT_UUID" = "true"
}

if (Test-Path $ClaudeSettings) {
    $settings = Get-Content $ClaudeSettings -Raw | ConvertFrom-Json
    if (-not $settings.env) {
        $settings | Add-Member -NotePropertyName "env" -NotePropertyValue @{}
    }
    foreach ($kv in $envBlock.GetEnumerator()) {
        $settings.env | Add-Member -NotePropertyName $kv.Key -NotePropertyValue $kv.Value -Force
    }
} else {
    $settings = @{ "env" = $envBlock }
}

$settings | ConvertTo-Json -Depth 10 | Set-Content $ClaudeSettings -Encoding UTF8

# Configure VS Code Copilot Chat
$VSCodeSettings = Join-Path $env:APPDATA "Code\User\settings.json"
if (Test-Path $VSCodeSettings) {
    $vsSettings = Get-Content $VSCodeSettings -Raw | ConvertFrom-Json
    $vsSettings | Add-Member -NotePropertyName "github.copilot.chat.otel.enabled" -NotePropertyValue $true -Force
    $vsSettings | Add-Member -NotePropertyName "github.copilot.chat.otel.exporterType" -NotePropertyValue "otlp-grpc" -Force
    $vsSettings | Add-Member -NotePropertyName "github.copilot.chat.otel.otlpEndpoint" -NotePropertyValue $Endpoint -Force
    $vsSettings | ConvertTo-Json -Depth 10 | Set-Content $VSCodeSettings -Encoding UTF8
    Write-Host "  Configured: VS Code Copilot Chat"
}

Write-Host "Flowstate telemetry configuration complete."
exit 0
`

// GenerateIntune writes a PowerShell script for Microsoft Intune deployment.
func GenerateIntune(w io.Writer, cfg config.Config) error {
	tmpl, err := template.New("intune").Parse(intuneTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	return tmpl.Execute(w, map[string]string{
		"Endpoint": cfg.Endpoint,
		"Key":      cfg.Key,
	})
}
