package mdm

import (
	"fmt"
	"io"
	"text/template"

	"github.com/meetflowstate/flowstate-telemetry/internal/config"
)

const jamfTemplate = `#!/bin/bash
# Flowstate Telemetry — Jamf Pro deployment script
# Generated by flowstate-telemetry generate-mdm --format jamf
# Deploy via Jamf Pro > Policies > Scripts
set -euo pipefail

ENDPOINT="{{ .Endpoint }}"
KEY="{{ .Key }}"

echo "==> Configuring Flowstate telemetry for all users..."

# System-wide environment variables
cat > /etc/flowstate-telemetry.env <<'ENVEOF'
FLOWSTATE_OTLP_ENDPOINT="{{ .Endpoint }}"
FLOWSTATE_OTLP_KEY="{{ .Key }}"
OTEL_RESOURCE_ATTRIBUTES="service.name=flowstate-telemetry"
ENVEOF
chmod 644 /etc/flowstate-telemetry.env

# LaunchDaemon to source env vars on login
cat > /Library/LaunchDaemons/inc.flowstate.telemetry.env.plist <<'PLISTEOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>inc.flowstate.telemetry.env</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>source /etc/flowstate-telemetry.env; launchctl setenv FLOWSTATE_OTLP_ENDPOINT "$FLOWSTATE_OTLP_ENDPOINT"; launchctl setenv FLOWSTATE_OTLP_KEY "$FLOWSTATE_OTLP_KEY"</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
PLISTEOF

# Configure Claude Code for each user
for HOMEDIR in /Users/*; do
    [ -d "$HOMEDIR" ] || continue
    USERNAME=$(basename "$HOMEDIR")
    [ "$USERNAME" = "Shared" ] && continue

    # Claude Code settings
    CLAUDE_DIR="$HOMEDIR/.claude"
    mkdir -p "$CLAUDE_DIR"
    SETTINGS="$CLAUDE_DIR/settings.json"

    if [ -f "$SETTINGS" ]; then
        # Merge with existing settings using Python (available on macOS)
        python3 -c "
import json, sys
with open('$SETTINGS') as f:
    s = json.load(f)
s.setdefault('env', {}).update({
    'CLAUDE_CODE_ENABLE_TELEMETRY': '1',
    'OTEL_METRICS_EXPORTER': 'otlp',
    'OTEL_LOGS_EXPORTER': 'otlp',
    'OTEL_EXPORTER_OTLP_PROTOCOL': 'http/protobuf',
    'OTEL_EXPORTER_OTLP_ENDPOINT': '$ENDPOINT',
    'OTEL_EXPORTER_OTLP_HEADERS': 'x-flowstate-key=$KEY',
    'OTEL_METRICS_TEMPORALITY_PREFERENCE': 'cumulative',
    'OTEL_METRICS_INCLUDE_SESSION_ID': 'true',
    'OTEL_METRICS_INCLUDE_ACCOUNT_UUID': 'true'
})
with open('$SETTINGS', 'w') as f:
    json.dump(s, f, indent=2)
"
    else
        cat > "$SETTINGS" <<CLAUDEEOF
{
  "env": {
    "CLAUDE_CODE_ENABLE_TELEMETRY": "1",
    "OTEL_METRICS_EXPORTER": "otlp",
    "OTEL_LOGS_EXPORTER": "otlp",
    "OTEL_EXPORTER_OTLP_PROTOCOL": "http/protobuf",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "$ENDPOINT",
    "OTEL_EXPORTER_OTLP_HEADERS": "x-flowstate-key=$KEY",
    "OTEL_METRICS_TEMPORALITY_PREFERENCE": "cumulative",
    "OTEL_METRICS_INCLUDE_SESSION_ID": "true",
    "OTEL_METRICS_INCLUDE_ACCOUNT_UUID": "true"
  }
}
CLAUDEEOF
    fi
    chown "$USERNAME" "$SETTINGS" "$CLAUDE_DIR"

    # Cursor hooks
    CURSOR_DIR="$HOMEDIR/.cursor"
    if [ -d "$CURSOR_DIR" ] || [ -d "/Applications/Cursor.app" ]; then
        mkdir -p "$CURSOR_DIR/hooks"
        # Hook script would be deployed separately or embedded here
        chown -R "$USERNAME" "$CURSOR_DIR"
    fi

    echo "  Configured: $USERNAME"
done

echo "==> Flowstate telemetry configuration complete."
exit 0
`

// GenerateJamf writes a Jamf Pro deployment script to the given writer.
func GenerateJamf(w io.Writer, cfg config.Config) error {
	tmpl, err := template.New("jamf").Parse(jamfTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	return tmpl.Execute(w, map[string]string{
		"Endpoint": cfg.Endpoint,
		"Key":      cfg.Key,
	})
}
