package mdm

import (
	"fmt"
	"io"
	"text/template"

	"github.com/meetflowstate/flowstate-telemetry/internal/config"
)

const puppetTemplate = `# Flowstate Telemetry — Puppet Manifest
# Generated by flowstate-telemetry generate-mdm --format puppet
# Deploy via Puppet: puppet apply flowstate-telemetry.pp

class flowstate_telemetry (
  String $endpoint = '{{ .Endpoint }}',
  String $key      = '{{ .Key }}',
) {

  # System-wide environment variables
  file { '/etc/profile.d/flowstate-telemetry.sh':
    ensure  => file,
    mode    => '0644',
    content => @("ENVEOF")
      export FLOWSTATE_OTLP_ENDPOINT="${endpoint}"
      export FLOWSTATE_OTLP_KEY="${key}"
      export OTEL_RESOURCE_ATTRIBUTES="service.name=flowstate-telemetry"
      | ENVEOF
  }

  # Configure Claude Code for each developer user
  $users = query_resources(false, ['=', 'type', 'User'])

  $users.each |$user_resource| {
    $username = $user_resource['title']
    $homedir  = $user_resource['parameters']['home']

    if $homedir and $homedir =~ /^\/home\// {

      # Claude Code settings
      file { "${homedir}/.claude":
        ensure => directory,
        owner  => $username,
        mode   => '0755',
      }

      file { "${homedir}/.claude/settings.json":
        ensure  => file,
        owner   => $username,
        mode    => '0644',
        content => @("CLAUDEEOF")
          {
            "env": {
              "CLAUDE_CODE_ENABLE_TELEMETRY": "1",
              "OTEL_METRICS_EXPORTER": "otlp",
              "OTEL_LOGS_EXPORTER": "otlp",
              "OTEL_EXPORTER_OTLP_PROTOCOL": "http/protobuf",
              "OTEL_EXPORTER_OTLP_ENDPOINT": "${endpoint}",
              "OTEL_EXPORTER_OTLP_HEADERS": "x-flowstate-key=${key}",
              "OTEL_METRICS_TEMPORALITY_PREFERENCE": "cumulative",
              "OTEL_METRICS_INCLUDE_SESSION_ID": "true",
              "OTEL_METRICS_INCLUDE_ACCOUNT_UUID": "true"
            }
          }
          | CLAUDEEOF
        require => File["${homedir}/.claude"],
      }

      # VS Code Copilot Chat settings
      $vscode_dir = "${homedir}/.config/Code/User"

      exec { "check-vscode-${username}":
        command => "/bin/true",
        onlyif  => "/usr/bin/test -d ${vscode_dir}",
      }

      file { "${vscode_dir}/settings.json":
        ensure  => file,
        owner   => $username,
        mode    => '0644',
        replace => false,
        content => @("VSCODEEOF")
          {
            "github.copilot.chat.otel.enabled": true,
            "github.copilot.chat.otel.exporterType": "otlp-grpc",
            "github.copilot.chat.otel.otlpEndpoint": "${endpoint}"
          }
          | VSCODEEOF
        require => Exec["check-vscode-${username}"],
      }

      # Gemini CLI settings
      file { "${homedir}/.gemini":
        ensure => directory,
        owner  => $username,
        mode   => '0755',
      }

      file { "${homedir}/.gemini/settings.json":
        ensure  => file,
        owner   => $username,
        mode    => '0644',
        replace => false,
        content => @("GEMINIEOF")
          {
            "telemetry": {
              "enabled": true,
              "target": "local",
              "otlpEndpoint": "${endpoint}",
              "otlpProtocol": "grpc",
              "logPrompts": false
            }
          }
          | GEMINIEOF
        require => File["${homedir}/.gemini"],
      }

      # Shell profile
      file_line { "flowstate-env-${username}":
        path  => "${homedir}/.bashrc",
        line  => "export FLOWSTATE_OTLP_ENDPOINT=\"${endpoint}\" FLOWSTATE_OTLP_KEY=\"${key}\"",
        match => '^export FLOWSTATE_OTLP_ENDPOINT=',
      }
    }
  }
}

include flowstate_telemetry
`

// GeneratePuppet writes a Puppet manifest for Flowstate telemetry deployment.
func GeneratePuppet(w io.Writer, cfg config.Config) error {
	tmpl, err := template.New("puppet").Parse(puppetTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	return tmpl.Execute(w, map[string]string{
		"Endpoint": cfg.Endpoint,
		"Key":      cfg.Key,
	})
}
