package proxy

import (
	"fmt"
	"sort"
	"strings"
)

// GeneratePAC returns the JavaScript source of a Proxy Auto-Config script
// that routes only allowlisted AI hostnames through the local daemon
// (proxyAddr, e.g. "127.0.0.1:47813") and returns DIRECT for everything else.
//
// The function is defensive on multiple axes:
//   - host comparison is case-insensitive (PAC engines are inconsistent here)
//   - the hardcoded fallthrough at the bottom is "DIRECT" — if nothing
//     matches, the request bypasses the daemon entirely
//   - duplicate hosts in the allowlist are deduped before emission so the
//     generated PAC stays short
//
// Browsers, OS-level PAC, and `networksetup -setautoproxyurl` all tolerate
// this style.
func GeneratePAC(proxyAddr string, allowlist *Allowlist) string {
	hosts := []string{}
	if allowlist != nil {
		hosts = allowlist.Hosts()
	}

	// Dedup + sort for stable output (matters for tests + diffability).
	seen := make(map[string]struct{}, len(hosts))
	clean := make([]string, 0, len(hosts))
	for _, h := range hosts {
		h = strings.ToLower(strings.TrimSpace(h))
		if h == "" {
			continue
		}
		if _, ok := seen[h]; ok {
			continue
		}
		seen[h] = struct{}{}
		clean = append(clean, h)
	}
	sort.Strings(clean)

	var b strings.Builder
	b.WriteString("// Auto-generated by flowstate-telemetry. Do not edit by hand.\n")
	b.WriteString("// Routes recognised AI provider hosts through the local Flowstate\n")
	b.WriteString("// telemetry daemon; everything else goes DIRECT.\n")
	b.WriteString("function FindProxyForURL(url, host) {\n")
	b.WriteString("  host = host.toLowerCase();\n")
	b.WriteString("  var aiHosts = [\n")
	for i, h := range clean {
		comma := ","
		if i == len(clean)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "    %q%s\n", h, comma)
	}
	b.WriteString("  ];\n")
	b.WriteString("  for (var i = 0; i < aiHosts.length; i++) {\n")
	b.WriteString("    if (host === aiHosts[i]) {\n")
	fmt.Fprintf(&b, "      return %q;\n", "PROXY "+proxyAddr)
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("  return \"DIRECT\";\n")
	b.WriteString("}\n")
	return b.String()
}
